### ISSUE TITLE
[bug] changing the backups path causes server crash on startup

### ISSUE THREAD

**Issue by serveradmin9912** [FTBTeam/FTB-Backups#38]
Hi,

I simply changed line 23 in the **ftbbackups-common.toml** to change the path of the backups folder.
Nothing else was changed in this config.

```
#Enables backups to run automatically.
auto = true
#If set to true, no messages will be displayed in chat/status bar.
silent = false
#The number of backup files to keep.
#More backups = more space used
#0 - Infinite
#Range: 0 ~ 32000
backups_to_keep = 12
#Timer in minutes.
#5 - backups every 5 minutes
#60 - backups every hour
#360 - backups every 6 hours
#1440 - backups once every day
#Range: 1 ~ 43800
backup_timer = 120
#0 - Disabled (output = folders)
#1 - Best speed
#9 - Smallest file size
#Range: 0 ~ 9
compression_level = 1
#Absolute path to backups folder.
folder = "D:\Backups\backup_minecraft\backup_gameserver_minecraft\server1\ftbbackups"
#Prints (current size | total size) when backup is done.
display_file_size = true
#Add extra files that will be placed in backup _extra_/ folder.
extra_files = []
#Maximum total size that is allowed in backups folder. Older backups will be deleted to free space for newer ones.
max_total_size = "50 GB"
#Only create backups when players have been online.
only_if_players_online = true
#Create a backup when server is stopped.
force_on_shutdown = false

#Advanced features that shouldn't be changed unless you know what you are doing.
[advanced]
	#Buffer size for writing files.
	#Range: 256 ~ 65536
	buffer_size = 4096
```

causes this:

```
[20Jul2021 15:35:50.639] [main/INFO] [ipsis.woot.setup.ModSetup/]: registerRecipeSerializer
[20Jul2021 15:35:50.889] [main/INFO] [Bookshelf/]: Registered 22 ingredient serializers.
[20Jul2021 15:35:50.889] [main/INFO] [Bookshelf/]: Registered 5 IRecipeSerializer entries in 0.28ms.
[20Jul2021 15:35:50.889] [main/INFO] [Botany Pots/]: Registered 3 IRecipeSerializer entries in 0.13ms.
[20Jul2021 15:35:51.822] [main/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry Biome: The object minecraft:the_end has been registered twice for the same name minecraft:the_end.
[20Jul2021 15:35:51.822] [main/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry Biome: The object minecraft:end_barrens has been registered twice for the same name minecraft:end_barrens.
[20Jul2021 15:35:51.824] [main/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry Biome: The object minecraft:small_end_islands has been registered twice for the same name minecraft:small_end_islands.
[20Jul2021 15:35:51.825] [main/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry Biome: The object minecraft:end_midlands has been registered twice for the same name minecraft:end_midlands.
[20Jul2021 15:35:51.826] [main/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry Biome: The object minecraft:end_highlands has been registered twice for the same name minecraft:end_highlands.
[20Jul2021 15:35:52.044] [main/INFO] [ModdingLegacy/structure_gel/Compat/]: Checking for biome dictionary registry methods in other mods.
[20Jul2021 15:35:52.855] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file ftbbackups-common.toml of type COMMON for modid ftbbackups
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:61) ~[forge:?]
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:104) ~[forge:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[forge:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_301]
	at java.util.Collections$SynchronizedCollection.forEach(Unknown Source) ~[?:1.8.0_301]
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[forge:?]
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:203) ~[forge:?]
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:45) ~[forge:?]
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?]
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid escapement: \B
	at com.electronwill.nightconfig.toml.StringParser.escape(StringParser.java:130) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.StringParser.parseBasic(StringParser.java:25) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:44) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:68) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:57) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.3.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.3.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.3.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.3.jar:?]
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.3.jar:?]
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.3.jar:?]
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:57) ~[forge:?]
	... 21 more
```

would be thankful for help

**Comment by serveradmin9912** [comment]
I found the problem on my own. 
This mod doesnt like windows paths. I had to change all the backslashes to normmal /.

like this: "D:/Backups/backup_minecraft/backup_gameserver_minecraft/server1/ftbbackups"

**Comment by MaxNeedsSnacks** [comment]
It's probably parsing the backslashes as control characters (`\n` as newline for example), so you would have to escape the backslashes themselves `D:\\Users\\...` (or just use forward slashes like you have here :P)
